### ISSUE TITLE
uninitialized constant ActionController::Base::Handles (NameError)

### ISSUE THREAD

**Issue by gerardp** [dadooda/handles_sortable_columns#1]
Rails 3.0.0

gem install handles_sortable_columns
Gemfile:
gem "handles_sortable_columns"

And restart the server (rails s):

/usr/lib/ruby/gems/1.8/gems/handles_sortable_columns-0.1.1/lib/action_controller/base/handles_sortable_columns.rb:2: uninitialized constant ActionController::Base::Handles (NameError)
        from /usr/lib/ruby/gems/1.8/gems/handles_sortable_columns-0.1.1/lib/handles_sortable_columns.rb:3
        from /usr/lib/ruby/gems/1.8/gems/handles_sortable_columns-0.1.1/lib/handles_sortable_columns.rb:2:in `each'
        from /usr/lib/ruby/gems/1.8/gems/handles_sortable_columns-0.1.1/lib/handles_sortable_columns.rb:2
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:64:in`require'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:64:in `require'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:62:in`each'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:62:in `require'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:51:in`each'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:51:in `require'
        from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.6/lib/bundler.rb:112:in`require'
        from /home/gerard/project/visualpis/config/application.rb:7
        from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0/lib/rails/commands.rb:28:in `require'
        from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0/lib/rails/commands.rb:28
        from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0/lib/rails/commands.rb:27:in`tap'
        from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0/lib/rails/commands.rb:27
        from script/rails:6:in `require'
        from script/rails:6

**Comment by dadooda** [comment]
Thanks Gerard.

I've actually haven't have a chance to test the gem with Rails 3 since the latter isn't stable enough yet.

I'll have a quick look and maybe come up with a solution.

Alex

**Comment by gerardp** [comment]
No, thanks for you work :)
I hope you find the solution.

**Comment by dadooda** [comment]
Gerard

Please have a look at gem version 0.1.2. Rails 3 support roughly seems to work. Any issues, please report.

Thanks.

Alex

**Comment by gerardp** [comment]
Daddoda

I update to version 0.1.2 and restart the server.
but stills i have a problem

"undefined local variable or method `handles_sortable_columns' for PisosController:Class"

class PisosController < ApplicationController
  handles_sortable_columns

  def index
    order = sortable_column_order
    @pisos = Piso.all(:order => order)

My view:
<%= sortable_column "P", :column => "p" %>

**Comment by dadooda** [comment]
Gerard

Are you sure you have a `gem "handles_sortable_columns"` in your `Gemfile`?

Alex

**Comment by gerardp** [comment]
Sorry!!
I forgot uncomment the gem.

It works perfect, thanks !!
