### ISSUE TITLE
Sorting in the context of other params

### ISSUE THREAD

**Issue by srogers** [dadooda/handles_sortable_columns#10]
From examining the code, it looks like the sort params should be merged with any other params that should be preserved (such as a search param) here:

sortable_columns.rb line 257:  url = url_for(params.merge( . . . .

but my sort links are always generated with just direction= and sort= params - it seems so simple, I can't imagine what could go wrong.  Any thoughts?

Rails 3.2.13 and handles_sortable_columns (0.1.4)

**Comment by dadooda** [comment]
Steve

Just checked, for me it worked, the params are merged. Try this:
1. Request a page you're column-sorting, e.g. `/users`.
2. Append a GET parameter voluntarily, e.g. `vlad=dracula`. Should render `/users?vlad=dracula`.
3. Request the page. Parameter `vlad` should stay.
4. Now click a sortable column. Parameter `vlad` should stay, `sort=column` should get appended.

Try this. If the parameter stays at step 3, it'll stay at step 4. If not, it means it's lost somewhere in the middle.

**Comment by srogers** [comment]
OK - thanks, I set it up in a clean project and it works for me there also, so it must be something peculiar about this specific project.

**Comment by dadooda** [comment]
Good luck. :)
