### ISSUE TITLE
Ajax sortable

### ISSUE THREAD

**Issue by kapil-kumar** [dadooda/handles_sortable_columns#15]
Hi can you please let me know how to do ajax for this gem.

Present we have 
<%= sortable_column "column_name" %> if I click it loading the page, but i want instead of loading total page i want to add ajax.

I haven't seen ajax functionality to this gem. Can you please anyone explain me how to add ajax for this sortable column.

**Comment by dadooda** [comment]
Kapil,

This gem is purely a server-side solution. I think these days for AJAX it's better to use JSON serialization on the server end and a proper JS UI built on top of a good framework, such as React.js.

Does it make any sense, what do you think?

**Comment by kapil-kumar** [comment]
Yes that was really very good solution. Will check that way.

Thanks for your quick solution..
