### ISSUE TITLE
how to change desc and asc indicator

### ISSUE THREAD

**Issue by AW-HTK** [dadooda/handles_sortable_columns#2]
i cant find the way to change the display of indicator ↓ and ↑ . 
in css i do: 
/***************_/
/_ sotable table */
/****************/

.asc{

  background: url(/images/up_arrow.gif) no-repeat;
}

.desc{
  margin-left: 10px;
  background-image: url(/images/down_arrow.gif);
}

and in the controller:
 handles_sortable_columns do |conf|
  conf.class = "SortableLink"
  conf.indicator_class = {:asc => "asc", :desc => "desc"}
end

what i did miss !!?
thanks.

**Comment by dadooda** [comment]
I suggest that you use an HTML/CSS debugging tool such as Firebug for
Firefox, or native HTML inspection tool of Chrome.

Inspect the element of up/down arrow to see if your configuration has
effect (class is assigned as desired).

Then, if it's all okay with the class, use the same tool to inspect
CSS properties.

----- Original Message -----
From: adelinoo reply@reply.github.com
To: alex.r@askit.org
CC: 
Time: Wed, 27 Apr 2011 05:10:04 -0700
Subject: [GitHub] how to change desc and asc indicator [dadooda/handles_sortable_columns GH-2]
Attachments: <none>

i cant find the way to change the display of indicator ↓ and ↑ . 
in css i do: 
/***************_/
/_ sotable table */
/****************/

.asc{

  background: url(/images/up_arrow.gif) no-repeat;
}

.desc{
  margin-left: 10px;
  background-image: url(/images/down_arrow.gif);
}

and in the controller:
 handles_sortable_columns do |conf|
  conf.class = "SortableLink"
  conf.indicator_class = {:asc => "asc", :desc => "desc"}
end

what i did miss !!?
thanks.

## 

Reply to this email directly or view it on GitHub:
https://github.com/dadooda/handles_sortable_columns/issues/2

**Comment by AW-HTK** [comment]
i did it befor posting and this is the code:
< th> < a href="/user_admins?page=1&amp;sort=username" class="SortableLink">username< /a> < /th> 
< th> < a href="/user_admins?page=1&amp;sort=email" class="SortableLink desc">email< /a> & n bsp; & uarr; & nb sp;< /th> 
< th> < a href="/user_admins?page=1&amp;sort=sign_in_count" class="SortableLink">sign_in_count< /a>< /th>

so like you see,the ↓ and ↑ symbol is writen ( &uarr; ) automatically,and if i change the css of the class and i put background-image, this image is added in space of the < th> but the ↓ and ↑ are always here !!!

**Comment by dadooda** [comment]
Ah, that's what you mean. That's the `indicator_text` configuration
parameter.

See the doc:
http://rdoc.info/github/dadooda/handles_sortable_columns/master/Handles/SortableColumns/Config

----- Original Message -----
From: adelinoo reply@reply.github.com
To: alex.r@askit.org
CC: 
Time: Wed, 27 Apr 2011 15:26:53 -0700
Subject: [GitHub] how to change desc and asc indicator [dadooda/handles_sortable_columns GH-2]
Attachments: <none>

i did it befor posting and this is the code:
<th> <a href="/user_admins?page=1&amp;sort=username" class="SortableLink">username</a> </th> 
<th> <a href="/user_admins?page=1&amp;sort=email" class="SortableLink desc">email</a>&nbsp;&uarr;&nbsp;</th> 
<th> <a href="/user_admins?page=1&amp;sort=sign_in_count" class="SortableLink">sign_in_count</a></th>

so like you see,the ↓ and ↑ symbol is writen ( &uarr; ) automatically,and if i change the css of the class and i put background-image, this image is added in space of the <th> but the ↓ and ↑ are always here !!!

## 

Reply to this email directly or view it on GitHub:
https://github.com/dadooda/handles_sortable_columns/issues/2#comment_1067067

**Comment by AW-HTK** [comment]
thanks for the help :) its ok now :)
