### ISSUE TITLE
how to change desc and asc query

### ISSUE THREAD

**Issue by AW-HTK** [dadooda/handles_sortable_columns#3]
hi
this gem dont use DESC and ASC methode of mysql. i see that it use just ' - ' befor the name of the column used to be sorted.
its there a way to fix it please?

**Comment by dadooda** [comment]
Please read examples in the README.

@@@
order = sortable_column_order do |column, direction|
  case column
  when "name"
    "#{column} #{direction}"
  when "created_at", "updated_at"
    "#{column} #{direction}, name ASC"
  else
    "name ASC"
  end
end
@@@

`direction` is "ASC" or "DESC".

Considering GET arguments, you are right, gem uses just parameter, where "-" before its value denotes DESC order.
