### ISSUE TITLE
undefined local variable or method `has_sortable_columns' for module

### ISSUE THREAD

**Issue by kakubei** [dadooda/handles_sortable_columns#6]
Pardon my ignorance, but I am getting this error:

```
undefined local variable or method `has_sortable_columns' for ModelFunctions:Module
```

When trying to use the plugin with some methods that I extend via a Module. 

I extend the `search` method inside my controller by redeclaring it again in the module since I used it with multiple controllers. Is there a way to get the search method in the Module to understand about the sortable columns? 

Thanks. 

And thanks for the plugin, it's very nice.

**Comment by dadooda** [comment]
Shouldn't it be **handles_** sortable_columns?

**Comment by kakubei** [comment]
Sorry, you are quite correct, didn't copy/paste properly. 

Furthermore the problem is that the module actually extends the Model, not the controller so I don't know if there is a solution in the current configuration I have.
